# Generated by Django 4.1.2 on 2022-11-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tearsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
