# Generated by Django 4.1.2 on 2022-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tearsapi', '0002_tag_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='image_src',
        ),
        migrations.AddField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='uploads/%Y/%M/%D'),
        ),
    ]
