# Generated by Django 4.1.2 on 2022-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tearsapi', '0003_remove_moment_image_src_moment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='image',
        ),
        migrations.AddField(
            model_name='moment',
            name='image_src',
            field=models.CharField(default='1.png', max_length=255),
        ),
    ]
